name: Build and Push Docker Image

on:
   push:
      branches:
         - main # or master, depending on your default branch name

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Login to Docker Hub
           uses: docker/login-action@v3
           with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}

         - name: Build and Push Docker Images
           run: |
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nvim:latest -f ./nvim.Dockerfile .
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/nvim:latest
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devenv:latest .
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/devenv:latest
